Access-Control-Allow-Origin: http://localhost:3000
Access-Control-Allow-Method: GET, POST, PUT , DELETE
Access-Control-Allow-Headers: Content-Type

### Auth

### Register
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "username": "Fatih",
    "email": "fatih@gmail.com",
    "password": "fatih",
    "no_hp": "081162732810",
    "address": "Jakarta",
    "division": "Accounting",
    "institute": "Universitas Gunadarma",
    "major": "Akuntansi"
}

### Register Mentor
POST http://localhost:3000/api/v1/auth/register/mentor
Content-Type: application/json

{
    "username": "Widya",
    "email": "widya@gmail.com",
    "password": "widya",
    "division": "HR"
}

### Login
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "kai.enim@gmail.com",
    "password": "kaienim"
}

### Update User
PUT http://localhost:3000/api/v1/auth/user/12
Content-Type: application/json

{
    "username": "Fatih Alfarizi",
    "email": "fatih@gmail.com",
    "password": "fatih",
    "no_hp": "081162732810",
    "address": "Jakarta",
    "division": "Accounting",
    "institute": "Universitas Gunadarma",
    "major": "Akuntansi"
}

### Update Mentor
PUT http://localhost:3000/api/v1/auth/mentor/4
Content-Type: application/json

{
    "username": "Widya Salim",
    "email": "widya@gmail.com",
    "password": "widya",
    "division": "HR"
}

### Get All User
GET http://localhost:3000/api/v1/auth/user?page=1&limit=5
Content-Type: application/json

### Get User By Id
GET http://localhost:3000/api/v1/auth/user/12
Content-Type: application/json

### Get All Mentor
GET http://localhost:3000/api/v1/auth/mentor?page=2&limit=2
Content-Type: application/json

### Get Mentor By Id
GET http://localhost:3000/api/v1/auth/mentor/3
Content-Type: application/json

### Delete User
DELETE http://localhost:3000/api/v1/auth/user/14
Content-Type: application/json

### Delete Mentor
DELETE http://localhost:3000/api/v1/auth/mentor/5
Content-Type: application/json

### Get Me
GET http://localhost:3000/api/v1/auth/me
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0NTM2MzU3fQ.aaTg_MrdBN7m5nxZvIgAloeuLCNfM6CUwc8ai5FTTsk





### Activity

### Add Activity
POST http://localhost:3000/api/v1/activity
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0NTEwODYyfQ.EjlPYLRwYRsHjNW-sF0PLgil-IrIZDwi44tL8-x1kx4
Content-Type: application/json

{
    "activity": "hapus ngab",
    "desc_activity": "hapus aja cok."
}

### Get All Activity
GET http://localhost:3000/api/v1/activity?page=2&limit=1
Content-Type: application/json

### GET User Activities
GET http://localhost:3000/api/v1/activity/user?page=1&limit=5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0NTM2MzU3fQ.aaTg_MrdBN7m5nxZvIgAloeuLCNfM6CUwc8ai5FTTsk
Content-Type: application/json

### Update Activities
PUT http://localhost:3000/api/v1/activity/13
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0NTM2MzU3fQ.aaTg_MrdBN7m5nxZvIgAloeuLCNfM6CUwc8ai5FTTsk
Content-Type: application/json

{
    "activity": "Create Login Page",
    "desc_activity": "Creating Login Page using bootstrap, required Email dan Password and little qoutes"
}

### Delete Activities
DELETE http://localhost:3000/api/v1/activity/16
Content-Type: application/json





### Project

### Update Project
PUT http://localhost:3000/api/v1/project
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzM0NTM2MzU3fQ.aaTg_MrdBN7m5nxZvIgAloeuLCNfM6CUwc8ai5FTTsk
Content-Type: application/json

{
    "project_title": "Login",
    "project_desc": "Login adalah abalblaalba"
}